language: php
php:
  - 5.5
  - 5.6
  - 7.0
addons:
  code_climate:
    repo_token: SET_ME
before_script:
  - sed -i '/phpdoc/d' composer.json
  - composer install
script:
  - phpunit --configuration test/phpunit.xml test
  - ./vendor/bin/phpcs --ignore=*/vendor/*,*/bootstrap.php --standard=PSR2 .
  - ./vendor/bin/phpcs --standard=./vendor/athens/standard/ruleset.xml src
after_script:
  - vendor/bin/test-reporter